<?xml version="1.0" ?>
<robot name="clumsybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_len" value="0.145"/>
  <xacro:property name="base_width" value="0.19"/>
  <xacro:property name="base_height" value="0.23"/>
  <xacro:property name="hat_protuding" value="0.01"/>
  <xacro:property name="hat_height" value="0.03"/>


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="metalic">
    <color rgba="0.9 0.9 0.95 1"/>
  </material>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}"/>
      <material name="metalic"/>
    </visual>
  </link>


  <link name="hat_link">
    <visual>
      <geometry>
        <box size="${base_len+hat_protuding} ${base_width+hat_protuding} ${hat_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="base_to_camera" type="fixed">
    <parent link="base_link"/>
    <child link="hat_link"/>
    <origin xyz="0 0 ${base_height}"/>
  </joint>
</robot>
