<?xml version="1.0" ?>
<robot name="clumsybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159"/>

  <xacro:property name="base_len" value="0.145"/>
  <xacro:property name="base_width" value="0.19"/>
  <xacro:property name="base_height" value="0.23"/>

  <xacro:property name="hat_protuding" value="0.01"/>
  <xacro:property name="hat_height" value="0.03"/>

  <xacro:property name="wheel_radius" value="0.021"/>
  <xacro:property name="wheel_width" value="0.007"/>
  <xacro:property name="wheel_clearance" value="0.005"/>


  <xacro:include filename="materials.xacro" />
  <xacro:include filename="clumsybot.gazebo" />


  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
      <material name="metalic"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width + 2*hat_protuding} ${base_height + hat_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" />
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_clearance}" rpy="0 0 0"/>
  </joint>


  <link name="hat_link">
    <visual>
      <geometry>
        <box size="${base_len+hat_protuding} ${base_width+hat_protuding} ${hat_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <joint name="base_to_hat" type="fixed">
    <parent link="base_link"/>
    <child link="hat_link"/>
    <origin xyz="0 0 ${base_height}" />
  </joint>



  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_color"/>
      <origin rpy="${PI/2} 0 0" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <joint name="left_front_wheel_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${-base_len/2 + wheel_radius} ${base_width/2} ${wheel_radius - wheel_clearance}"/>
  </joint>

  <link name="left_back_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_color"/>
      <origin rpy="${PI/2} 0 0" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <joint name="left_back_wheel_joint" type="continuous">
    <mimic joint="left_front_wheel_joint" offset="0" multiplier="1" />
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin xyz="${base_len/2 - wheel_radius} ${base_width/2} ${wheel_radius - wheel_clearance}"/>
  </joint>


  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_color"/>
      <origin rpy="${PI/2} 0 0" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <joint name="right_front_wheel_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="${-base_len/2 + wheel_radius} ${-base_width/2} ${wheel_radius - wheel_clearance}"/>
  </joint>

  <link name="right_back_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_color"/>
      <origin rpy="${PI/2} 0 0" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <joint name="right_back_wheel_joint" type="continuous">
    <mimic joint="right_front_wheel_joint" offset="0" multiplier="1" />
    <axis xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin xyz="${base_len/2 - wheel_radius} ${-base_width/2} ${wheel_radius - wheel_clearance}"/>
  </joint>

</robot>
